### ISSUE TITLE
Missing code for specific demo

### ISSUE THREAD

**Issue by mid787** [alexziskind1/ndd#1]
Hi Alex :)

I want through ( for the past 2 weeks ) on every video , presentation of yours and including the youtube's codes for "The Art of Mobile App Interaction " - which are in this git - NDD.

But one is missing ( the one which I've wanted the most : 

![image](https://user-images.githubusercontent.com/2842123/34074469-528941e0-e2b8-11e7-8246-0ac73a934b04.png)

Where you click on item and it's animate to a full screen

Can you please provide a link for the code ? or at least can you _please_ describe how you did it ?

(A reference to code would be much appreciated).

**Thank you :)**

**Comment by alexziskind1** [comment]
Hi Royi,

Thanks for checking this out. 
I have to say that this particular demo is not in this repo because it is a very unpolished piece of code that was for a demo than anything else. It shows what’s possible, but by no means it is a guide on how to do this. 
I believe Shiva Prasad (on the Slack channel) is making this into a more reusable solution. 
Could you please check with him about the status of his plugin?

Alex

**Comment by mid787** [comment]
Sure . Thank you for your reply.
